apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
spec:
  selector:
    app: fastapi-app  # Match the label from your Deployment
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005  # Port on which your FastAPI application is running inside the container
  type: NodePort  # Change to ClusterIP or NodePort based on your requirements
